# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysql:
    type: mysql
    disk: 1024

redis:
    type: redis

solr:
    type: solr
    disk: 1024

mongodb:
    type: mongodb:3.0
    disk: 1024

